### ISSUE TITLE
Custom hotkey

### ISSUE THREAD

**Issue by IsaacsLaughing** [gemforce-team/wGemCombiner#15]
A bit of a niche issue, granted, but the current key does not function normally on my keyboard, so the option to set our own would be much appreciated.

**Comment by 12345ieee** [comment]
See #14.
The code is already in place, it's just a matter of testing and releasing (as usual I cannot test, due to lack of Windows)

**Comment by 12345ieee** [comment]
Released new version with the requested feature.
Closed.
