### ISSUE TITLE
Release 1.0.8

### ISSUE THREAD

**Issue by 12345ieee** [gemforce-team/wGemCombiner#16]
@gemforce-team/wgemcombiner 
I made some extra modifications on top of the beta branch, IMHO it's ready to release, IFF it works (can you check, @CooLTanG ?)

Contents:
* Base gems list box ( see #10 )
* Selectable combine hotkey (see #14 and #15 )
* Bug fixes and various enhancements

**Comment by CooLTanG** [comment]
Yeah looks good, I forgot those 1-6 keys, nice job fixing that.

**Comment by 12345ieee** [comment]
@CooLTanG 
Be careful, the tag you attached the release to is 2 commits behind the .exe you put.
This time was something minor (your contribution list) but be more careful.

I made a new v1.0.8a tag at the tip of master and pointed the release there, all is fixed.

**Comment by CooLTanG** [comment]
Yeah if wouldn't let me use that 1.0.8 tag probably cuz of the one u put up. It wouldn't let me upload the exe for awhile either, even switched browser.  But ya minor change there.
