### ISSUE TITLE
Update recipes

### ISSUE THREAD

**Issue by 12345ieee** [gemforce-team/wGemCombiner#18]
Hi @CooLTanG 
time to update the recipes, here there are all the ones currently in gemforce repo:
https://gist.github.com/12345ieee/58dfd9d012160381a1b9#file-recipes-txt

One of them is longer than 1M, you'll probably need to adjust the boxes a bit, if you can.

If you can make recipe long 7 digit to work (1M-9.9M) I'll write up the one I have till 4M and send them.

**Comment by 12345ieee** [comment]
EDIT: Sorry, I sent a commend wrong, there you have all of them up to 16k
I'll send the ones up to 1M later

**Comment by CooLTanG** [comment]
I've added them, just can't figure out why its not loading them up.  I'm looking into it though, I'll let ya know.

**Comment by 12345ieee** [comment]
Now, I don't recall exactly how the loader worked but it would be nice to be able to load them as I gave them to you.
There might be some problems with recipes long 4 (which should not be in wGC) that I left in the file by error.
I hope the new recipes are correctly replacing the corresponding old ones.

I have also some problem to retrieve the recipes bigger than 16k (I won't be able to look into this for several days) due to the way I put them on gemforce repo, maybe we can find a more stable way (like a file with all the parenthesis line by line that I update for every new recipe)

**Comment by CooLTanG** [comment]
Ok got it working, had some issues, but it should be all working now that I tested it.  I'll update to another release in a day or 2.

**Comment by 12345ieee** [comment]
There was a huge mess with your commits.
I squashed them all in a single commit and pushed to branch `rc`.

I have also made an error in the combines I gave you, most of the recipes you have are probably not the correct ones, sorry.

I'll try to fix this stuff later this week, sorry for the time wasted.

**Comment by CooLTanG** [comment]
np, let me know and I'll update em

**Comment by 12345ieee** [comment]
Will be part of a bigger rework, I close this for the moment.
