### ISSUE TITLE
Steam Version, combine not working

### ISSUE THREAD

**Issue by rschurade** [gemforce-team/wGemCombiner#19]
When I run an upgrade recipe, for example the simple orange combine, I end up with a few grade 1 and 2 gems because the combine doesn't seem to work. In the process I see the "bomb" button getting activated quite a few times.

Also when trying to follow the recipes manually, the game places new gems in the right most available column. For our orange combine example, that means new gems go to 1C, 1B, 2C.

**Comment by 12345ieee** [comment]
What version of wGC are you using?

**Comment by rschurade** [comment]
1.0.8

**Comment by rschurade** [comment]
1.0.8 the top download on the release page.

2015-08-20 16:32 GMT+02:00 Andrea Stacchiotti <notifications@github.com>:

**Comment by 12345ieee** [comment]
This is a job for @CooLTanG (I am on Linux)

**Comment by CooLTanG** [comment]
Orange combine just requires the orange gem alone in the bottom right slot (1A), which is where your mouse cursor should be over too when you press '9'.  From the sound of your post you have it over 1C (bottom left).  If I'm wrong try combining with the window reset (go into options and click "Set default window size")

**Comment by CooLTanG** [comment]
I should make that clearer without having to go to the help files probably.

**Comment by rschurade** [comment]
Oops, well sorry. Who would have thought it's right to left :)
