### ISSUE TITLE
kg218226C fails

### ISSUE THREAD

**Issue by RobinHood70** [gemforce-team/wGemCombiner#20]
When the above recipe is finished, the final gem is one level short of what it should be, and there's an extra (start + 2) lvl gem left over.

Yes, I know it says it might not work, but in repeated testing, it follows the same pattern every time, so it clearly doesn't work and should be fixed/removed.

**Comment by 12345ieee** [comment]
On Linux wGC crashes if I try to even select it, and I have currently no access to Windows.

I had actually to update all the recipes, as you can see [here](https://github.com/gemforce-team/gemforce/tree/master/results/killgem-combine) the kg218226C isn't even an optimal combine anymore, but I've not had time to do that.

I'm sorry, but unless somebody's willing to have a look at the 36+ slots folding code, there's noting to be done.

**Comment by RobinHood70** [comment]
Okay, fair enough. Just for the record, there's also a bug in the kg262144C instructions as well...again, probably from the 36+ code. Between steps 2802-2805, it combines everything on row 12 onto 12B, then duplicates 12C, which of course is now empty.

I might have a go at the code myself over the next couple of days, but since I find it kind of amazing that you figured out a way of doing that in the first place, I'm not sure I'll be much help. Hopefully, I'll understand the logic behind the wizardry once I start looking at it. :)

**Comment by 12345ieee** [comment]
The reason I was/am not able to fix the folding code is because I didn't write it in the first place.
That part is due to Suuper, I worked on other parts.

Around 75% of the combines that have to be folded have some sort of problem, if you want to look at it, good luck.

**Comment by RobinHood70** [comment]
Thanks, I'll probably need it! :P

**Comment by RobinHood70** [comment]
Got it! I just created a 262144 kill combine successfully for the first time ever. I'll look into uploading the code tomorrow, but I'm definitely gonna fork the project, cuz I basically did a total overhaul on just about everything, and updated the code to C# 6 at the same time.

**Comment by 12345ieee** [comment]
Congratulations!

Looking forward to take a peek at it.

Maybe we can sneak in the new recipes and release a v1.1, let me know.

**Comment by RobinHood70** [comment]
Okay, I forked it and uploaded the new copy. I’m very new to Git and even newer to GitHub, so let me know if I did anything that causes issues when cloned to another machine. (Specifically, I’m wondering about the packages.config and the ruleset.)

**Comment by 12345ieee** [comment]
I'll have a look now.
You can find me on the #gemforce channel at freenode if you want to discuss (I may have several question) and can help you with git

**Comment by 12345ieee** [comment]
Sorry, the #gemcraft channel.
Whatever, I'm in both now.

**Comment by 12345ieee** [comment]
You can find here an example of a file I can easily generate for you to parse:
[leech.txt](https://github.com/gemforce-team/wGemCombiner/files/43914/leech.txt)

If it's fine, I'll upload all the other recipes.

**Comment by RobinHood70** [comment]
Looks good. I’m just starting on reading text files now. Shouldn’t take too long.

**Comment by RobinHood70** [comment]
Since this is now fixed, I'm closing this issue.
