### ISSUE TITLE
run as admin needed

### ISSUE THREAD

**Issue by davehale** [gemforce-team/wGemCombiner#22]
for info and not request for fixing as i'm more than happy running it as admin

os is win 7
gemcraft latest version
.net is 4.5

game exe is in "C:\Program Files (x86)\Steam\steamapps\common\GemCraft Chasing Shadows\GemCraft Chasing Shadows.exe
combiner exe is in C:\Users\dave\Favorites\Desktop\wGemCombiner-master\WGemCombiner-v1.1\WGemCombiner-v1.1\WGemCombiner.exe
I start both from desktop shortcuts

checked permissions for user 'dave'  to c:\users\dave(and beyond) and all ticked,

running as non admin i can click combine and move mouse over gem. pressing the hotkey will make the combine 'counter'/eta meter move but mouse will not move. if i do a long combine and move the mouse and click the combine app window mid combine, the mouse will start moving (but obviously mid combine and its focus on where i clicked and not on A1.

i also get the file issues mentioned in the error message i posted (will repost here is needed?)

as a side to those file issues - when i manually created those files first and ran as non admin all is fine,(will recheck that is correct).

running the app as admin has zero issues.

the old app ran without the focus/interaction with the game window.

i'll move the app exe out of my user dir's once my latest endurance is over and see if that makes any difference. will also relog system on as a guest and see what happens there too.

as i say, this does not need fixing for me as it works when running as admin, but if you want to delve into it just say if you need any screen shots of stuff or me to change things this end

**Comment by davehale** [comment]
as a side to those file issues - when i manually created those files first and ran as non admin all is fine,(will recheck that is correct).

As in the file issues are. The game focus / mouse movement is still inactive

**Comment by davehale** [comment]
only moved wgem exe to "C:\Program Files (x86)\wgem" and opened with shortcut on desktop whilst still logged as user dave and both issues solve, no idea why running the exe as non admin from within dave's desktop dir stops file creation in appdata folder yet from where it is now is fine. And super shrug on the mouse issue.

still if anyone else has or reports similar issues its at our end and easily solved.

**Comment by 12345ieee** [comment]
Uhm...
My current guess is: `C:\Users\dave\Favorites\Desktop\wGemCombiner-master\WGemCombiner-v1.1\WGemCombiner-v1.1\WGemCombiner.exe` is a path too long for some function we use, whilst `C:\Program Files (x86)\wgem` is not. Or maybe dashes or dots are hated by some other function.

@davehale : could be of huge help if you could try out some different length of path (simply lengths, subfolders probably don't matter) and paths with dashes or dots.

@RobinHood70 : I'll try to have a look, but I'm not sure my VM can replicate this, otherwise I'll leave it to you.

Thank for the followup, @davehale .

**Comment by davehale** [comment]
with wgem exe running as non admin from 

C:\Users\Guest 
C:\Users\dave
C:\Users\dave\Favorites
C:\Users\dave\Favorites\temp

all is fine. 


running from original place at  C:\Users\dave\Favorites\Desktop\wGemCombiner-master i get  both issues.



if i simply right click, copy and paste the folder i get the same issues with the copied exe now at  C:\Users\dave\Favorites\Desktop\wGemCombiner-master - Copy 

then (.... and it gets stranger )

if i rename that folder to C:\Users\dave\Favorites\Desktop\wGemCombiner-master2 all works
however if i then rename that folder or even as 1st rename to 'C:\Users\dave\Favorites\Desktop\wGemCombiner-master new'  both errors reoccur 

or if i copy and move the working C:\Users\dave\Favorites\Desktop\wGemCombiner-master2 folder to C:\Users\dave\Favorites\wGemCombiner-master2 without any other changes both issues return


i have a properties option to unblock the exe's (working ones or not) as its from another computer yet in all the above cases that makes no difference

changing the exe name in any location it does not work has no effect but changing it to wgem.exe in moved/renamed folder locations where it then works causes the exe to mis behave again.

there is obviously some sort of security / access issue with my system and the exe that makes no sense to me. grabbing another fresh exe download and dropping it to c:\ before dropping it onto my desktop. btw i do have git installed on my comp so maybe the fact i've downloaded the source via that and the exe direct has it scratching its head

**Comment by 12345ieee** [comment]
I'm completely appalled (and also completely unable to replicate the problem on my system).

I have only one question, you said you downloaded the source, did you by any chance compile the original .exe by yourself?

Because VS runs as admin by default, which might have a role here.
If that is the problem, grabbing a fresh .exe should solve it.

**Comment by davehale** [comment]
half solved it.

the exe is running with the user group  Users(dave-HP\Users) permissions despite me being logged in and downloaded the exe while on as dave(dave-HP\dave)

**Comment by davehale** [comment]
yeap i did compile, but fresh download after all traces of old deleted has same issues but due the app not installing(?) with my user permissions but defaulting to generic user group permissions

allowing it write as a permission for that user group solves both. removing write however obviously prevents config file creation but disables the app from mouse control when not focused on the wgem app window. still no idea why it wont pick up my permissions as the user logged on and defaulting to generic User group

**Comment by davehale** [comment]
the exe 's properties security tab deff says the exe owner is dave(dave-HP\dave) and i'm deff logged on as that user. But anyway, i can get it to run and it works a treat so unless others are struggling to get it to work for the same reason i'm happy to run it as administrator

**Comment by 12345ieee** [comment]
Not really an "error", just the closest label I have.
I'll now close it, as I believe it's on the @davehale 's end, nothing we can't do.

If there is additional information feel free to reopen it
