### ISSUE TITLE
Combine button not working

### ISSUE THREAD

**Issue by jforr** [gemforce-team/wGemCombiner#24]
I have Gemcraft loaded and running in default window size.  When I press combine and then the combine hotkey, nothing appears to happen.  I see wgemcombiner is working and runs through the steps, but no mouse movement on my end.

I loaded up some old versions of the application and in 1.05 the mouse does move, but mouse clicks don't appear to be registering so no actual combines take place.  I increased the delay to 1000 and it does appear that the mouse if moving the correct distances to hit the right buttons and gem slots, it just isn't clicking when it gets there.

1.05 is the last version where mouse movement occurs after attempting a recombine.

If there's anything I can do to help debug this, point me in the right direction and I'll do what I can.

**Comment by RobinHood70** [comment]
Try going into the options and selecting "Using Internet Explorer" (even if you're not). See if that helps. And if it does, and you're not using IE, please let us know so that we can change the wording appropriately.

**Comment by jforr** [comment]
This is on the steam version, but there is no mouse movement at all with or without the internet explorer option checked.

**Comment by RobinHood70** [comment]
Hmmm...that's odd. It's even odder that an old one would work and the new one doesn't, as the mouse movement routines are essentially the same. Which OS are you on? And just to cover all the bases, what happens if you try using "Run as Administrator"?

**Comment by jforr** [comment]
Run as administrator did the trick, so probably just something to through into the FAQ.  This was on Windows 7 Pro.

**Comment by RobinHood70** [comment]
That's the second time we've seen that on a Windows 7 machine. Very odd. Unfortunately, I don't have access to one to figure out the exact nature of the problem.

**Comment by 12345ieee** [comment]
@RobinHood70 We need to find out exactly what causes this problem, I propose writing about it in the readme and help and having an issue with people reporting their full system config (win version, NET runtime, etc...).

We can time this with v1.1.1 release, which I wanted to do in some days (I made some changes I wanted to get out)

**Comment by RobinHood70** [comment]
I just did some quick Googling, and apparently both keybd_event and mouse_event, which we're using, were deprecated a long time ago and may be unreliable. The recommendation was to use SendInput(). I'll look into it more when I have time, hopefully tomorrow.

**Comment by RobinHood70** [comment]
A little more Googling on SendInput found a much more in-depth response on the actual problem. If I'm reading this right, running as admin may be the only viable solution, but I'll look into self-signing and such as well.
http://stackoverflow.com/questions/22714374/how-to-programmatically-click-the-mouse-in-another-program-when-this-code-doesn

**Comment by 12345ieee** [comment]
I am closing this, as there is nothing we can really do.
