### ISSUE TITLE
Change default combine key

### ISSUE THREAD

**Issue by jforr** [gemforce-team/wGemCombiner#25]
I'm recommending a small suggestion to change the default combine key to a tilde " ` " key.  With multiple monitors it's easy to press your combine hotkey on another window and have it go crazy.

There might be issues with laptops or other smaller keyboards where the tilde is missing or requires a function key.

Also an option to pause hotkey detection without closing the app might also work well.

**Comment by RobinHood70** [comment]
Yeah, I really don't like the '9' key, myself. I have no objection to changing it to a back-quote, though I'm not sure how easy it is to access on international keyboards.

**Comment by 12345ieee** [comment]
A back-tick in the Italian keyboard is `Alt-Gr + ì`, not something easy to access.
Also, you cannot trigger the combine when you have a modifier key pressed, to let people type `Shift + 9` without problems.

There is an option to change the key exactly for this reason, I see no point in changing the default value.

**Comment by 12345ieee** [comment]
Well, closing, as there is nothing to do.

If @jforr happens to have stronger arguments for a default key change, he/she can reopen this.
