### ISSUE TITLE
debug modus

### ISSUE THREAD

**Issue by deuter75** [gemforce-team/wGemCombiner#26]
after ca. 1 hour of playing the game (~e30 mana), the combiner starts to produce unpredictable stones.
i play in default resolution, set it back to default resolution when the problem occures, restart the combiner, set the delay from 50 to 100, from 100 to 150, change combining steps - but the issue still remains.
I studied a bit the combinercode, and saw there is a outcommented section with a message box that shows the resolution, and my guess is, that something with that isn't right on my pc. so could you please add a debug option, so that that message box (and maybe some other infos are logged in a file) is shown? 
thx in advance,
deuter

**Comment by 12345ieee** [comment]
If the combiner gets the right gems at the beginning the resolution is right.
Your problem is that you need a bigger delay when there are many monsters on screen, try to up it to ~500.

**Comment by deuter75** [comment]
ok - thank you very much!
i'll give it a try :)

**Comment by deuter75** [comment]
works pefect!
thx 12345ieee :)

**Comment by 12345ieee** [comment]
Great to know, @deuter75 .
I'm closing this.
