### ISSUE TITLE
Combine button not working

### ISSUE THREAD

**Issue by lumpy007** [gemforce-team/wGemCombiner#28]
Hi,
I am using win7 and the game is running on firefox. When i press the 9 button and my cursor is in a text editor it will write only .(hiding info) d(for duplicate) and u(upgrade) letters but no g(combine). Tried on the game too in a good scaling but the gems are put on each other instead of combining it. Tried to use with Using Internet Explorer button but still not functioning.

**Comment by RobinHood70** [comment]
Try running it as an administrator. That's been the problem most of the time people have experienced issues like this.

**Comment by lumpy007** [comment]
The administrator rights is not helping, also tried to set the process priority higher but still no g button.

**Comment by RobinHood70** [comment]
No, the g button wouldn't be expected. It uses the menu button to do combines, not the g key. (Combines were failing with the g key at high speeds, but don't when using the mouse.)

I've tried it in Win 10 on the latest version of Firefox and everything looks okay there, so I'm not sure what to suggest. I don't have Windows 7 available to test with.

**Comment by 12345ieee** [comment]
Zoom level & fullscreen, the browser game must be at the original resolution for wGC to work (otherwise we don't hit the combine button).

**Comment by lumpy007** [comment]
You are right i was only close to the normal resolution, with a more precise window scaling it is working.

**Comment by 12345ieee** [comment]
Nice to hear, I'll be sure to emphasize this more in the help.
Solved & closed.
