### ISSUE TITLE
It might, or might not be a bug

### ISSUE THREAD

**Issue by emilking91** [gemforce-team/wGemCombiner#3]
It could be something on my end, or my own error.

OS - Windows 7 SP1 64-bit
Game Version:
      Steam - 1.0.2
      Armor Games - 1.1.12
WGemCombiner v1.0.6b

https://www.youtube.com/watch?v=2Aqy-hdcU3c

Description: Basically the simplest formula doesn't work with the auto combiner. Either it duplicates gems if only 1, or it combines the gems if there are 4 gems already. In neither scenario does it upgrade the first gem.

**Comment by 12345ieee** [comment]
Note for me: this is clearly the keypress transfer bug, like Astro had.
Fix is already in testing branch.

**Comment by 12345ieee** [comment]
Ok, here are 3 different builds.
Try to play around with the delay settings, let's hope one of these work.
https://www.dropbox.com/s/l4j8jldqb9kj9eg/WGemCombinerX3.zip?dl=0

**Comment by 12345ieee** [comment]
EDIT: If those do not work I have an even uglier hack to try, that should work, but I really hope I don't need to resort to that.

**Comment by emilking91** [comment]
Update: After some testing on the debug version, I came to the realization that the issue comes from the fact that when the combination is happening, the window selection is not focused on the game. After testing it both on the debug and released version, I can confirm that the combiner works perfectly ONLY IF the window that is focused is the game window.

**Comment by 12345ieee** [comment]
Glad it all worked out
