### ISSUE TITLE
Spec 8o better then Orange Combine 00000064* 0,495855 ???

### ISSUE THREAD

**Issue by zachanassian** [gemforce-team/wGemCombiner#31]
OS - Windows 10 (64 Bit)
Game Version:
Steam - 1.0.6
WGemCombiner v1.1.1

Learnt about this program today and thought i would give it a try. Works perfectly with steam.

However results are astonishing. At least to me. Maybe I missed something. I tried the Kill Spec specs but the resulting gems were worse then the gems I produced by simply 'u' a gem like r3y4b

So I thought maybe I do something wrong and switched the simple orange gems. Expectation was that I get a gem that is better in terms of leech then the simple 8o gem.

But I got:

Spec (Orange Combine 00000064* 0,495855):
(((((((((((((2o+o)+o)+o)+o)+2o)+2o)+2o)+(2o+o))+((2o+o)+o))+(((2o+o)+o)+o))+(((((2o+o)+o)+o)+o)+2o))+((((((2o+o)+o)+o)+o)+2o)+3o))+(((((((2o+o)+o)+o)+o)+2o)+3o)+4o))

Result:
Damage 319-759
Range 7.2
shots/s 1.27
Leeches 21.72 mana/hit
Mana Value 5374

Spec: 7o

Result:
Damage 352-779
Range 7.3
shots/s 1.46
Leeches 33.39 mana/hit
Mana Value 5374

I know that there is some kind of random() involved combining gems. But I did this 10 times. Always 8o produces better gems then "Orange Combine 00000064* 0,495855".

I guess I miss something pretty obvious but I am unable to figure it out. Any help is appreciated.

**Comment by 12345ieee** [comment]
This does not make sense.
64c for orange has a higher growth than 8c (obviously), so at the same cost the 64c gem is better.

The randomness in gem combination enters only in damage, and even then it's very very tiny once you are at high levels.

Your 1.5x loss of leech is explainable only with a messed up 64c I guess.
Try running it at high delay (or even manually, once), to check if it's the case.

**Comment by zachanassian** [comment]
First I have to apologize for a typo. I have compared 7o vs Orange Combine 00000064* because both are 64c gems. I updated this in the original posting now.

I also found my error. I compared "Orange Combine 00000064*" vs 7o and had mana leech skill set to 45.

"Orange Combine 00000064*" will give a grad 6 gem that does only get an 180% boost from skill mana leech

7o will give a grad 7 gem that gets an additional 75% (180% + 75%) from skill mana leech.

So only error was that I tried to experiment with the program using very low mana gems. Whenever the grad of a spec build gem is greater then 6, then it will be the best gem for the given mana. If it is below grad 7 the effect of skills might disturb the direct comparison.

Sorry for the confusion. Topic can be closed.

For reference if somebody else wants to check:

Case A using Orange Combine 00000064* vs 7o
A1) Set Skill
Mana Leech 0

Used Spec: (Orange Combine 00000064*)
Result:
Grad 6
Leeches 3.07 mana/hit

which is better then 7o (great!):
Grad 7
Leeches 2.69 mana/hit

A2) Set Skill
Mana Leech 45

Used Spec: (Orange Combine 00000064*)
Result:
Grad 6
Leeches 8.59 mana/hit

which is worse then 7o (wtf):
Grad 7
Leeches 13.2 mana/hit

Case B using Orange Combine 00000128* vs 8o
Set Skills
Mana Leech 0

Used (Orange Combine 00000128*)
Result:
Grad 7
Leech 4.34

which is better then 8o (great!):
Result:
Grad 8
Leech 3.72

Set Skills
Mana Leech 45

Used (Orange Combine 00000128*)
Result:
Grad 7
Leech 21.26

which is better then 8o (great!):
Result:
Grad 8
Leech 18.21

**Comment by 12345ieee** [comment]
I'm not sure I follow about the '7o' stuff, you won't get 2 gems of the same value that way, but I'm happy it's solved.

Of course, comparing gems across grade 7 gives nonsensical answers, bring both over g7 first to experiment.

Definitely closed.
