### ISSUE TITLE
Discussion for release v1.1.90

### ISSUE THREAD

**Issue by 12345ieee** [gemforce-team/wGemCombiner#33]
If the people that are trying the beta will provide feedback, here is where I directed them.
@Makaifren , @BilboCGL you're both invited (you 2 might want to watch the repo, so you get all the ~~spam~~ notifications automatically)

PR #32 is still the place to discuss about the code, I had a couple questions that I left earlier.

Announcement is here: https://steamcommunity.com/app/296490/discussions/0/451848855005729494/
Related release is here: https://github.com/gemforce-team/wGemCombiner/releases/tag/v1.1.90

For whoever want to share their opinion, we need to know your OS (Windows version at 32/64 bit) and the GC version (browser/standalone/Steam) you're playing on.

**Comment by neofisGG** [comment]
Hi guys, i try the new release and it did very well.

I used my last combinaison method, and the responses are fast.

I keep going and try to follow my master :) SatoshiSama

**Comment by BilboCGL** [comment]
No idea why I didn't see that before - switching through the buttons with tab has a "grown order" From top-left to button-right would be more intuitiv.

**Comment by 12345ieee** [comment]
Eh, the widgets have an "id" that starts from 1 (or was it 0) and goes on. That is the tabbing order.

The id is assigned each time a new widget is created.
Basically by tabbing you can follow the coding history, as we never bothered to reorder them.

It's not difficult to change, just tedious to go through the editor and change each one.

**Comment by BilboCGL** [comment]
Thought so. Sorry for that, but when you try to tab from "delay field" to "combine button" it's just not funny when you suddenly change the recipe by adding some tabstops.

**Comment by 12345ieee** [comment]
@BilboCGL Actually MS made that much more easier that I thought.
It took 5 mins to reorder all the controls.

Run the attached [WGemCombiner-v1.1.90-2.zip](https://github.com/gemforce-team/wGemCombiner/files/273754/WGemCombiner-v1.1.90-2.zip) and tell me.

**Comment by Makaifren** [comment]
It used to be control-D while looking at the designer

**Comment by BilboCGL** [comment]
Fine, thanks! Now it is way more easier to activate the combine with keyboard after changing the delay.
No idea if it is avoidable, after reaching the recipes field, you fill this field with tabs, Not really a problem, just a bit ugly.

**Comment by 12345ieee** [comment]
@Makaifren It's not Ctrl+D any more, it's under the View menu.

@BilboCGL It's a textbox, the default behaviour when you press TAB is to insert an actual TAB character. I'd really prefer not changing it.

**Comment by Kadoffe01** [comment]
Hi,
the new gem combiner works really fine and what is absolutely the best - you can now doing other stuff during combining gems  cause the cursor is free now :-)

**Comment by Makaifren** [comment]
I'm totally going to change it.  Tab isn't needed there anyway.  I want to
say there's a flag for the control which says if it wants ENTER or other
special navigation characters.

**Comment by Makaifren** [comment]
I'm using the GitHub site now, and couldn't figure out how to get into conversation #32, I also can't seem to send private messages to other users. Still trying to figure the system out.  I have the github desktop client installed now (corporate network problem resolved).

**Comment by Makaifren** [comment]
I was really close to redoing the project using C++ WTL to create a 15k .exe that would run on Windows 98 and later, with no dependencies; then decided that would have been pedantic since I don't think users are actually having problems with windows versions.

**Comment by 12345ieee** [comment]
Yeah, PR #32 is a tad difficult to find because the code has been merged, so the thread was put in the closed PR section.
In case the #32 itself is not a link, it is at `https://github.com/gemforce-team/wGemCombiner/pull/32`

You cannot send a PM to other github users, if you need to privately contact me, send an email.

----------

wGC depends on .NET framework 4.5, which excludes every Windows older than Vista, but really, I can't imagine that GC runs well in a XP era PC.

**Comment by 12345ieee** [comment]
So, nobody complained about the new method, I'm going to assume it works with all the combinations of GC/OS.

As such, I plan to release v1.2 in the weekend.
If somebody has some feature that wants to include for 1.2 (either a reasonable request or a piece of already written code), let me know before Saturday.

**Comment by neofisGG** [comment]
The program works well for me. I try it during 1 week and it's fine.

**Comment by 12345ieee** [comment]
wGC version 1.2 released:
https://github.com/gemforce-team/wGemCombiner/releases/tag/v1.2.0
with almost no changes from the beta.

Closing this.
