### ISSUE TITLE
Virus detected in latest release.

### ISSUE THREAD

**Issue by jonypawks** [gemforce-team/wGemCombiner#35]
When I downloaded the 1.2 release it tripped the windows defender virus scanner as a trojan with the identity: Trojan:Win32/Fethar.B!cl

The previous beta release does not have this issue.

**Comment by quinor** [comment]
If you want to use current version, try to compile it yourself, there is no
virus in code I assure you ;). I'm rather sure that it's false positive,
but we'll check anyway.

niedz., 26.06.2016 o 19:30 użytkownik Jesse Printz <notifications@github.com>
napisał:

**Comment by jonypawks** [comment]
Thanks for the fast response!  Yeah, I was pretty sure it was a false positive but thought I'd let you know just in case.

**Comment by 12345ieee** [comment]
Again, there is no trojan here, you can compile it yourself and verify that the resulting binary is the same we distribute.

Can we have more info on the scan result? (e.g. what OS, what version of WinDef, more scan details, etc...)

**Comment by jonypawks** [comment]
I'm on Windows 10, up to date with latest definitions in Windows Defender, I haven't made any changes to the default Windows 10 install regarding virus protection.

The quarantine window doesn't really give me much more information than just the name of the threat and this link: https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fFethar.B!cl&threatid=2147708975&enterprise=0

**Comment by 12345ieee** [comment]
Of course that page gives exactly 0 info on what this trojan actually is. Thanks Microsoft.
Looking it up on google, there are a sleeve of false positives and nothing else.

I'm not going to bother with the extremely convoluted process to report wGC as safe, if @quinor wants, he can do it, otherwise this is `WONTFIX`.

**Comment by 12345ieee** [comment]
Well, I see @jonypawks agrees with me.
Closing this, thanks for reporting.
