### ISSUE TITLE
wGemCombiner stopped working properly today

### ISSUE THREAD

**Issue by Kromwell-1** [gemforce-team/wGemCombiner#37]
i am using windows 8.1 with the latest update of firefox as my browser. i play gemcraft chasing shadows on armorgames.com.

the issue i am having is the killgem spec / coeff amps stopped working correctly. it does not make the gem recipe i selected and does not finish the recipe, leaving several gems uncombined. i have over 150,000 mana available, so its not a mana issue. the resulting gems vary. combine seems to work fine, but i have not played long enough since the problem started to use any of the recipes bigger than 128 combine.

another symptom i have noticed is after using the gem combiner my mouse-over information in the game no longer works. for such things as selecting target priority and looking at the info panel, i can no longer access that. everything worked fine until about 2 hours ago, when i just finished playing field X5 and earning 76+ billion XP (no endurance). it started after that when i was trying to farm field E3 for shadow cores.

if it will help i can make a video of what the gem combiner does. i am new to this so i may need a hand figuring how to send the video and if there are size limits on file size.

**Comment by Kromwell-1** [comment]
ok, i found some settings that had strangely been changed. the info on mouse-over is working again, but still failed to complete the higher recipes. i did manage to get a 256 spec to work just now though.

**Comment by Sibusten** [comment]
Have you tried increasing the delay between actions? If it is going too fast, key and mouse actions could be getting lost or skipped over, which would break recipes and leave gems uncombined.

wGemCombiner hides tooltips while combining gems as it helps to reduces lag. It does this using a hotkey, so if that keypress is lost the tooltips would stay hidden. Try increasing the delay to 100 (instead of 50) and see if that fixes the issue.

**Comment by Kromwell-1** [comment]
i have a short video to send but i dont see a way to send it or attach it

**Comment by Kromwell-1** [comment]
i just increased it to 150 on the delay. it successfully did a 342122 combine, and then failed a 16384

**Comment by Kromwell-1** [comment]
ahh, so it changes the tooltip while combining and then changes it back when done? if so, that would be how it got changed. it just didnt switch it back.

**Comment by Kromwell-1** [comment]
i am going to try restarting the laptop. it has a problem with restarts, due to needing new batteries,  so it may be several hours before it is up and running again.

**Comment by Kromwell-1** [comment]
well it starts up much better with no battery installed. hopefully the combiner will work again now

**Comment by Sibusten** [comment]
Hopefully the restart and increase to delay will fix the problem. If you still have issues with it, and are sure that you have set the gems up properly, you can try lowering more graphics settings to further reduce lag, and increasing the delay further.

**Comment by Kromwell-1** [comment]
ok, it still fails when trying a 1024 spec, much less a 2048 spec. this is at a delay of 200, 300, and even 500. it is also using more slots than what it says. i have all slots empty, so that isnt an issue, but for a 1024 it is supposed to use 20 slots and its using 26.

the end result should be a level 10 gem in slot A1, but i get a level 9 in slot 1A and a 2b in slot 5C, a 2B+B in slot 5B and a 3b gem comprised of some combination of 19 level 1 black gems

**Comment by Kromwell-1** [comment]
there really isnt any lag at all. this is at the very start of the game, so there are no monsters yet. it was working fine yesterday with 15000 monsters on the screen.

**Comment by Kromwell-1** [comment]
i am going to guess that since it is using more slots than it should that it is missing some combine steps along the way, considering that it is leaving behind orphan gems when it is finished

**Comment by Kromwell-1** [comment]
strangely it isnt the ones in the slots that are beyond the range of slots it should be using. maybe it is losing its y-axis mouse position somewhere along the way?

**Comment by Kromwell-1** [comment]
it seems the best gems i can make are limited to 256 now. i might consider doing a 1024 by hand, but when i want to do a 4 million+ combine that is simply not possible, LOL

**Comment by Kromwell-1** [comment]
the restart didnt help :(

**Comment by RobinHood70** [comment]
It sounds to me like something's going wrong on your end, as opposed to the specific formulas being wrong. Your guess about the mouse y-axis position being off would make a lot of sense. If you post exactly which formulas you're using, though, hopefully someone can test them and confirm that it's not the formulas themselves. (I'm afraid I can't right now, as I'm not currently actively playing the game.)

What are you using to play? The Steam version? A website version? Or have you gotten experimental and created a standalone version for yourself? (Not common, but a couple of people have done it.)

**Comment by Kromwell-1** [comment]
at the beginning, i use the mana spec 1024 and the kill spec 1024. it seems all the bigger recipes fail. 256 is hit and miss and only ones lower than 256 seem to be consistent. changing the delay has no effect at all, except takes longer. before my first posting i had rare failures, and i used all the largest recipes.  my biggest gems were 2048 spec and upgraded 3 times with 307075 for mana and 3 times with 4062424 for kill gem. i have no clue what changed so suddenly.

**Comment by Kromwell-1** [comment]
my last run was a nice one. 3 talisman fragments and all were level 100s

**Comment by 12345ieee** [comment]
This is a place for strictly technical discussion, @Kromwell-1 , not to write about how your last game went.

The combiner used to work, and suddenly it doesn't work anymore, for sure there's nothing we did wrong, the change was in your system, but there is no way to know till you answer @RobinHood70 's question.

Please keep your answers to the point.

**Comment by Kromwell-1** [comment]
its in my first post. i play on armorgames

**Comment by 12345ieee** [comment]
So, did Firefox recently update? Flash support is slowly going away and I'd not be surprised if it keeps getting more and more sandboxed.

Maybe take a look at https://support.mozilla.org/en-US/kb/adobe-flash-protected-mode-firefox , as mentioned in the README.

**Comment by RobinHood70** [comment]
If recipes are hit or miss, then it's definitely not the recipes themselves that are the issue, it'll be something to do with the mouse. Make sure you're playing at 100% window size and that your mouse is perfectly centered in the starting slot. Apart from that, it's been too long since I worked on this project for me to offer any other advice.

**Comment by Kromwell-1** [comment]
the web page is at 100%. the game itself has no options to increase or decrease the window size.

**Comment by Kromwell-1** [comment]
i just tried it with protected mode switched off. i tried each recipe starting at highest kill spec abd it failed each time until i got down to 256 spec. i thank you guys for the help. i know the problem isnt the combiner. i am just trying to find out what is causing it

**Comment by 12345ieee** [comment]
Good luck, @Kromwell-1 , if you find out what the cause was we'll be happy to hear it.
