### ISSUE TITLE
Possible bug with combines

### ISSUE THREAD

**Issue by Xalynden** [gemforce-team/wGemCombiner#4]
OS - Windows 8.1 64-bit
Game Version:
Steam - 1.0.2
WGemCombiner v1.0.6b

https://youtu.be/Oi2enUG2W-U

Any combines I do seem to stop partway through. In the video you'll see me start with a grade 5, do a 16 combine and end up with a grade 5 and a grade 7.

All other combines I've tried give me 1 grade lower than it should.

As an example, I tested a 64 combine (starting at grade 5) and ended up with a single grade 9(should have been grade 10 since 64c gives +5 to grade).

Speccing seems to be working just fine.

If more info is required please let me know.

**Comment by 12345ieee** [comment]
This likely seems a lag issue.
Try to do the combine slower and disabling info boxes and tell me if there are still problems.

**Comment by Xalynden** [comment]
Thank you for the suggestion 12345ieee. While testing this suggestion I figured out what the problem was. The issue apparently came from the fact that after hitting combine I was just hovering my mouse over the gem and hitting 9 without clicking on the window to make it the active window first. If I bring the window in focus first and then hit 9 there is zero issue. Thanks for the suggestion and thanks for making such a great program:)

Also, I'm getting paid today so I'll be donating a bit to this project.
