### ISSUE TITLE
wGemCombiner working under Wine

### ISSUE THREAD

**Issue by Azkaas** [gemforce-team/wGemCombiner#41]
Hey! Im using this under wine and the macros are working fine for me. Just wanted to let you know, since the README.md states that it doesnt.

Im using Arch with both gnome and Qtile

Thanks for the awesome program!

**Comment by 12345ieee** [comment]
Wine got better lately it seems.

I think you'll want to check out the combiner mod for a more built-in experience:
https://github.com/gemforce-team/gemsmith

**Comment by Azkaas** [comment]
Thanks! Im running gemsmith for GC:FW, but afaik it doesnt work with GC:CS?

**Comment by 12345ieee** [comment]
It actually does, but it might not be well documented yet.

Anyway closing, thanks for the heads-up.
