### ISSUE TITLE
Combining Stopping

### ISSUE THREAD

**Issue by jdguy99** [gemforce-team/wGemCombiner#6]
I have had problems with the combine just stopping part way through.  i tried following suggestions made both on other issues here and on the steam forum.  I got it to work once out of at least 10 tries.  not sure what other info you need from me.

Thanks
JD

**Comment by 12345ieee** [comment]
This has got to be the vaguest bug report ever.
There is no wGC version.
No mention of what OS you run,
No mention of which recipes you tried, nor what the final result you get is.

I need enough information so that I can reproduce the issue or there is no way I can understand/fix it.

**Comment by 12345ieee** [comment]
Nothing more followed, I assume it was a user error.
