### ISSUE TITLE
combining steps failing

### ISSUE THREAD

**Issue by Luzzifus** [gemforce-team/wGemCombiner#8]
I'm on Win7 using GCCS Steam version. I downloaded the latest release of wGemCombiner (1.0.6b) and read all the very well written instructions behind the "Help" button.

I tried with managem and killgem specs and the problem seems to be that the program never does combining steps, it only dupes and upgrades. To illustrate:

For example I pick the 8s killgem preset, the first instructions of that are:
0: Dupe 1A
1: Comb 1A + 1C
2: Comb 1C + 2A
3: Dupe 1B
4: Comb 2A + 1B
5: ...

Now I put g1 yellow into 1A (bottom right), g1 black into 1B (bottom middle) and g1 red into 1C (bottom left). Pick the spec, klick on "Get Instructions", then "Combine", focus the game, turn tooltips off, put mouse over yellow gem (1A) and hit "9". Now the combiner does the following for each of the above steps:

0: Dupe g1 yellow, new gem goes to 2A.
1: Move mouse pointer to 1C, nothing more happens.
2: Move mouse pointer to 2A, nothing more happens.
3: Move mouse pointer to 1B and dupe g1 black, new gem goes to 2B.
4: Mouse pointer stays at 1B, nothing more happens.

Sometimes on the combine steps, the two gems get switched instead of doing nothing. But most of the time they do not. They are never actually combined. 

I tried with default delay as well as with 1000ms to comprehend the behaviour. Also doesn't matter if the game is in fullscreen or windowed (and with the respective flag set in wGemCombiner).

**Comment by 12345ieee** [comment]
I have a vague idea what the problem behind it can be.
Could you repeat the same test on the web version at armorgames.com?

**Comment by Luzzifus** [comment]
Tried on armorgames, same result.
Do you want me to make a video?

**Comment by 12345ieee** [comment]
More useful would be the output log of the debug versions in issue #3 , could you try them?

**Comment by Luzzifus** [comment]
--------------------------------------------
WGemCombinerPK.exe
--------------------------------------------

05.06.2015 11:05:59
Performing a combine:
Moved cursor to   0   {X=1148,Y=658}
Duped gem in slot   0   {X=1148,Y=658}
Moved cursor to   0   {X=1148,Y=658}
Combining gems    0 and 2
Moved cursor to   2   {X=1092,Y=658}
Combining gems    2 and 3
Moved cursor to   1   {X=1120,Y=658}
Duped gem in slot   1   {X=1120,Y=658}
Moved cursor to   3   {X=1148,Y=630}
Combining gems    3 and 1
Moved cursor to   0   {X=1148,Y=658}
Duped gem in slot   0   {X=1148,Y=658}
Moved cursor to   1   {X=1120,Y=658}
Combining gems    1 and 0
Moved cursor to   2   {X=1092,Y=658}
Duped gem in slot   2   {X=1092,Y=658}
Moved cursor to   2   {X=1092,Y=658}
Upgrd gem in slot   2   {X=1092,Y=658}
Moved cursor to   2   {X=1092,Y=658}
Combining gems    2 and 1
Moved cursor to   0   {X=1148,Y=658}
Combining gems    0 and 1

--------------------------------------------
WGemCombinerSK.exe
--------------------------------------------

05.06.2015 11:04:19
Performing a combine:
Moved cursor to   0   {X=1145,Y=665}
Duped gem in slot   0   {X=1145,Y=665}
Moved cursor to   0   {X=1145,Y=665}
Combining gems    0 and 2
Moved cursor to   2   {X=1089,Y=665}
Combining gems    2 and 3
Moved cursor to   1   {X=1117,Y=665}
Duped gem in slot   1   {X=1117,Y=665}
Moved cursor to   3   {X=1145,Y=637}
Combining gems    3 and 1
Moved cursor to   0   {X=1145,Y=665}
Duped gem in slot   0   {X=1145,Y=665}
Moved cursor to   1   {X=1117,Y=665}
Combining gems    1 and 0
Moved cursor to   2   {X=1089,Y=665}
Duped gem in slot   2   {X=1089,Y=665}
Moved cursor to   2   {X=1089,Y=665}
Upgrd gem in slot   2   {X=1089,Y=665}
Moved cursor to   2   {X=1089,Y=665}
Combining gems    2 and 1
Moved cursor to   0   {X=1145,Y=665}
Combining gems    0 and 1

--------------------------------------------
WGemCombinerSKW.exe
--------------------------------------------

05.06.2015 11:06:54
Performing a combine:
Moved cursor to   0   {X=1151,Y=660}
Duped gem in slot   0   {X=1151,Y=660}
Moved cursor to   0   {X=1151,Y=660}
Combining gems    0 and 2
Moved cursor to   2   {X=1095,Y=660}
Combining gems    2 and 3
Moved cursor to   1   {X=1123,Y=660}
Duped gem in slot   1   {X=1123,Y=660}
Moved cursor to   3   {X=1151,Y=632}
Combining gems    3 and 1
Moved cursor to   0   {X=1151,Y=660}
Duped gem in slot   0   {X=1151,Y=660}
Moved cursor to   1   {X=1123,Y=660}
Combining gems    1 and 0
Moved cursor to   2   {X=1095,Y=660}
Duped gem in slot   2   {X=1095,Y=660}
Moved cursor to   2   {X=1095,Y=660}
Upgrd gem in slot   2   {X=1095,Y=660}
Moved cursor to   2   {X=1095,Y=660}
Combining gems    2 and 1
Moved cursor to   0   {X=1151,Y=660}
Combining gems    0 and 1

**Comment by CooLTanG** [comment]
Yes I had that problem too, I even coded a change to the combiner program.  This problem exists because you are outside the default window size of: 1088x612.  You can fix this easily, by resetting the window by going to Options -> Set default game window size.

**Comment by Luzzifus** [comment]
However, positioning the mouse pointer correctly doesn't seem to be the problem. Also it does not work in fullscreen mode either.

**Comment by 12345ieee** [comment]
@CooLTanG that's exactly why I asked him to use the AG version, but we'll see if things change once we cleaned up your pull request.
Sadly I can't make test builds right now, need to wait 1-2 days.

**Comment by CooLTanG** [comment]
Even with the AG version, you can enlarge your screen (zoom page) and it'll mess up, cuz he's outside the bounds of the default height of 600 if its the AG version.

**Comment by Luzzifus** [comment]
@CooLTanG: 
I didn't do that when I was testing.

But you seem to be right: I am at a different PC now where I didn't have this problem before. And I tried to set window mode and resized the window. This indeed reproduced the bug and it was fixed again when resetting the window size or going to fullscreen.

That's the major difference to the other PC where I initially encountered the problem: Fullscreen didn't fix it there either and also not the (definitely) default window size of the AG version.

**Comment by CooLTanG** [comment]
The fullscreen feature (the toggle in options on the combiner program), will only work if your screen has a 16:9 ratio also, not sure if u have that or not.  That's assuming ur talking about the Steam Version too, I don't think that works for AG version, since I can't find a place to fullscreen it.

**Comment by Crnimile** [comment]
I have same problem. But if i turn off "Show info panels" ingame then it start working normal.

**Comment by dubloe7** [comment]
It only works in 16:9? So the reason it doesn't work is because my monitor has a monitor aspect ratio instead of a television aspect ratio? The weird part to me is that as far as I can tell the program is trying to click on the combine button and hitting the amplifier button instead, that seems needlessly harder than just sending the combine shortcut key.

Are there any plans to fix this in the future?

**Comment by CooLTanG** [comment]
I have fixed this feature on my release, located here: 
https://github.com/CooLTanG/wGemCombiner/releases

Although it does still click the combine button because its faster in terms of operations, I tried the other way already.

**Comment by dubloe7** [comment]
That's the version I was using though (1.0.6b), so it appears I may have a different problem. Any suggestion as to what to try?

**Comment by CooLTanG** [comment]
It's actually version 1.0.7, the creators have been too busy to add it to their own git, but it's on my own one with the link above.

**Comment by 12345ieee** [comment]
Ok, at this point is clear I can't keep up with this.
I have another month of internship, a month of exams, then I need to reinstall Windows to work on wGC, I clearly can't do this.

@CooLTanG If you feel like picking this project up, send me an email and we'll arrange a more permanent solution.

**Comment by CooLTanG** [comment]
Sure, you can add me to the team anytime

**Comment by 12345ieee** [comment]
There's not only that...
@CooLTanG 
Can you drop on the IRC channel #gemcraft on freenode.net? I have a couple things I'd like to talk with you.

**Comment by dubloe7** [comment]
I see, I wasn't paying enough attention evidently. Thank you for your help.

**Comment by 12345ieee** [comment]
A direct link for you @CooLTanG 
https://kiwiirc.com/client/irc%3A%2F%2Firc.freenode.net%2Fgemcraft

**Comment by CooLTanG** [comment]
k there
